### PR TITLE
feat: add and configure husky for git linting

### LINKED ISSUE #15: feat: Add and configure husky package for commit messages
Inline with mainheartng/organization#11 
Add and configure `husky` package into the Backend API

### PR DESCRIPTION
**Pull request by inidaname**
For commit checks in respect of mainheartng/organization#11 to help developers follow our [Git Guides](https://github.com/mainheartng/organization/blob/main/gitflow-general.md), `hustky` has been installed and configured on the API project. This close #15 

This requires that all devs must update codes to latest on their local machines.

**With this config husky will check and restrict commit if it doesn't follow our rules**

Read more for our rules [Here](https://github.com/mainheartng/organization/blob/main/gitflow-general.md),

### CODE REVIEW

**Comment by mxhdiqaim** [comment]
@inidaname  IDK much about these two file ```.husky/commit-msg``` and ```commitlint.config.cjs```

What of configuration of the pre-commit hooks for ```husky``` and linting it in the ```package.json```

**Comment by inidaname** [comment]
> @inidaname IDK much about these two file `.husky/commit-msg` and `commitlint.config.cjs`
> 
> What of configuration of the pre-commit hooks for `husky` and linting it in the `package.json`

@mxhdiqaim `commitlint` is package that simplifies the process of configure githooks with husky, I was having drawbacks using only husky.

**Comment by mxhdiqaim** [comment]
@inidaname  With ```husky```, you will configure the pre-commit hook in the ```package.json``` see below.

```
"husky": {
  "hooks": {
    "pre-commit": "npm run lint"
  }
}
```

Then Add a ```lint``` script to your ```scripts``` section in ```package.json```
```
"scripts": {
  "lint": "eslint src"
}
```

But don't stress about it, since ```commitlint``` does same thing much simpler

**Comment by inidaname** [comment]
> But don't stress about it, since commitlint does same thing much simpler

Okay I will be looking forward to your review approval before merge

**Review by hallydon — APPROVED** [review]

**Review by mxhdiqaim — APPROVED** [review]

**Comment by mxhdiqaim** [comment]
@inidaname Approved!!!

**Pull request merged**
